/// Flutter icons SIde_Bar_icon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SIde_Bar_icon
///      fonts:
///       - asset: fonts/SIde_Bar_icon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SIdeBarIcon {
  SIdeBarIcon._();

  static const _kFontFam = 'SIde_Bar_icon';
  static const String? _kFontPkg = null;

  static const IconData ic_log_out =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_pending_payment =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_products =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_setting =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_leads =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_staff =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_today_order =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_calender =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_customer_and_orders =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_dashboard =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ic_none=
  IconData(0xeff, fontFamily: _kFontFam, fontPackage: _kFontPkg);


}
